version: '3.4'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
    - postgres-data:/var/lib/postgresql/data
    env_file:
    - .env
    ports:
      - 5432:5432
  nestjs:
    container_name: nestjs
    depends_on: 
      - postgres
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000

volumes: 
  postgres-data:
  nestjs-data:
