version: '3.4'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
    - "5432:5432"
    volumes:
    - postgres-data:/var/lib/postgresql/data
    env_file:
    - .env

  nestjs:
    container_name: nestjs
    image: nestjs
    depends_on: 
      - postgres
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      NODE_ENV: production
    ports:
      - 5050:5050

volumes: 
  postgres-data:
  nestjs-data:
