version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
    - "5432:5432"
    volumes:
    - postgres-data:/var/lib/postgresql/data
    env_file:
    - .env
 
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
    - "5050:80"
    env_file:
    - .env

volumes: 
  postgres-data:
